[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for production models"
authors = [{name="Lakshya Hidau", email="lakshyahidau2005@gmail.com"}]

[tool.setuptools]
packages = { find={} }

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}