name: Vehicle Insurance CI-CD

on:
  push:
    branches:
      - main
    paths:
      - "Project_01_Vehicle_Insurance_Data/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Hugging Face Docker Registry
      - name: Login to Hugging Face
        run: |
          echo "${{ secrets.HF_TOKEN }}" | \
          docker login huggingface.co \
            -u "${{ secrets.HF_USERNAME }}" \
            --password-stdin

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t huggingface.co/${{ secrets.HF_USERNAME }}/vehicle-insurance-docker:latest \
            ./Project_01_Vehicle_Insurance_Data

      # Step 4: Push Docker image to Hugging Face Space
      - name: Push Docker image
        run: |
          docker push huggingface.co/${{ secrets.HF_USERNAME }}/vehicle-insurance-docker:latest
