name: Vehicle Insurance CI-CD

on:
  push:
    branches:
      - main
    paths:
      - "Project_01_Vehicle_Insurance_Data/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Hugging Face Docker Registry
        run: |
          echo "${{ secrets.HF_TOKEN }}" | \
          docker login registry.hf.space \
            -u learncode2025 \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t registry.hf.space/learncode2025/vehicle-insurance-pred-app:latest \
            ./Project_01_Vehicle_Insurance_Data

      - name: Push Docker image
        run: |
          docker push registry.hf.space/learncode2025/vehicle-insurance-pred-app:latest
